#!/bin/bash

set -e

if [ -f /etc/default/octohost ]; then
  . /etc/default/octohost
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $DIR/env

run_mysql_command ()
{
  mysql -u$ADMIN_MYSQL_USER -p$ADMIN_MYSQL_PASSWORD -h$MYSQL_HOSTNAME -e "$1"
}

create_mysql_user ()
{
  # TODO: Check if user exists.
  SQL="CREATE USER '$1'@'%' IDENTIFIED BY '$2';"
  run_mysql_command "$SQL"
}

create_mysql_password ()
{
  cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
}

reload_mysql_tables ()
{
  SQL="FLUSH PRIVILEGES;"
  run_mysql_command "$SQL"
}

create_mysql_database ()
{
  # TODO: Check if DB exists.
  SQL="CREATE DATABASE $1"
  run_mysql_command "$SQL"
}

give_mysql_access ()
{
  SQL="GRANT ALL PRIVILEGES ON $1.* To '$1'@'%' IDENTIFIED BY '$2';"
  run_mysql_command "$SQL"
}

link_environment_variables ()
{
  /usr/bin/octo config:set $1/MYSQL_USERNAME "$1" > /dev/null
  /usr/bin/octo config:set $1/MYSQL_PASSWORD "$2" > /dev/null
  /usr/bin/octo config:set $1/MYSQL_DATABASE "$1" > /dev/null
  /usr/bin/octo config:set $1/MYSQL_HOSTNAME "$MYSQL_HOSTNAME" > /dev/null
}

show_environment_variables ()
{
  octo config $1
}

config_check () {
  if [ -z "$MYSQL_HOSTNAME" ]; then
    echo "MYSQL_HOSTNAME needs to be set in $DIR/env."
    exit 1
  fi
}

drop_mysql_database ()
{
  SQL="DROP DATABASE $1"
  run_mysql_command "$SQL"
}

drop_mysqL_user ()
{
  SQL="DROP USER $1"
  run_mysql_command "$SQL"
}

remove_environment_variables ()
{
  /usr/bin/octo config:rm $1/MYSQL_USERNAME
  /usr/bin/octo config:rm $1/MYSQL_PASSWORD
  /usr/bin/octo config:rm $1/MYSQL_DATABASE
  /usr/bin/octo config:rm $1/MYSQL_HOSTNAME
}

case "$1" in

  mysql:create)
  config_check
  if [ $2 ]; then
    USER="$2"
    echo "Creating user and database for '$USER' container."
    PASSWORD=$(create_mysql_password)
    create_mysql_user "$USER" "$PASSWORD"
    create_mysql_database "$USER"
    give_mysql_access "$USER" "$PASSWORD"
    reload_mysql_tables
    link_environment_variables "$USER" "$PASSWORD"
    show_environment_variables "$USER"
    echo "TO BE ADDED: octo reload $USER"
  else
    echo "Usage: octo mysql create {container}"
  fi
  ;;

  mysql:delete)
  config_check
  if [ $2 ]; then
    USER="$2"
    drop_mysql_database "$USER"
    drop_mysqL_user "$USER"
    reload_mysql_tables
    remove_environment_variables "$USER"
    echo "TO BE ADDED: octo reload $USER"
  else
    echo "Usage: octo mysql delete {container}"
  fi
  ;;

  help)
  cat<<EOF

  octo mysql:create {container}
  octo mysql:delete {container}
EOF
  ;;

  *)
  ;;
esac
